export type Status = "Not Started" | "In Progress" | "Blocked" | "Complete";
export type Priority = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";

export interface Task {
  id: string;
  phase: string;
  owner: string;
  description: string;
  priority: Priority;
  monthTarget: string;
  status: Status;
  notes: string;
}

export interface Workstream {
  id: string;
  name: string;
  objective: string;
  owner: string;
  monthTarget: string;
  tasks: Task[];
}

export const WORKSTREAMS: Workstream[] = [
  {
    id: "rcm",
    name: "Operations / RCM",
    objective: "Audit network RCM/billing model, evaluate options (continue outsource, re-bid, or insource), and execute the chosen path including payment options (CareCredit, payment plans, etc.) unify sliding scale/financial hardship plan",
    owner: "Ops/RCM Lead",
    monthTarget: "Month 1–6",
    tasks: [
      { id: "rcm-1", phase: "RCM Audit", owner: "Ops/RCM Lead", description: "Pull 90-day claims report from MHS outsourced RCM vendor — compare denial rate, days-in-AR, clean-claim rate, and collections rate against Radial benchmarks", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Establish performance baseline before any decisions are made" },
      { id: "rcm-2", phase: "RCM Audit", owner: "Ops/RCM Lead", description: "Map full MHS payer portfolio (CA Medi-Cal, Premera WA, BCBS multi-state, Aetna, UHC, Cigna) — compare contracted rates against Radial's current rates by CPT code", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Flag payers where MHS rates exceed or trail Radial" },
      { id: "rcm-3", phase: "RCM Audit", owner: "Ops/RCM Lead", description: "Review MHS outsourced vendor contract — document termination clause, notice period, SLAs, and any performance penalties", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Need to understand exit ramp before any decision is made" },
      { id: "rcm-4", phase: "RCM Audit", owner: "Ops/RCM Lead", description: "Document MHS billing workflow end-to-end: intake, charge capture, claim submission, adjudication, payment posting, and denial management", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "Gap analysis vs Radial workflow — input to decision" },
      { id: "rcm-5", phase: "RCM Audit", owner: "Ops/RCM Lead", description: "Identify which billing platform the MHS vendor uses — assess compatibility or migration complexity if a path change is chosen", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "rcm-6", phase: "RCM Decision", owner: "Ops/RCM Lead", description: "Build RCM options analysis: (1) continue outsourcing with current vendor, (2) re-bid outsourcing to a new vendor, (3) phased insourcing to Radial RCM team — score each on cost, risk, timeline, and alignment", priority: "CRITICAL", monthTarget: "Month 2", status: "Not Started", notes: "DECISION NOT YET MADE — this analysis is the prerequisite" },
      { id: "rcm-7", phase: "RCM Decision", owner: "Ops/RCM Lead", description: "Present RCM recommendation to leadership — include financial model, transition risk, and recommended path with rationale", priority: "CRITICAL", monthTarget: "Month 2", status: "Not Started", notes: "Decision drives all subsequent RCM tasks" },
      { id: "rcm-8", phase: "RCM Standards", owner: "Ops/RCM Lead", description: "Establish shared KPI dashboard: clean claim rate, denial rate, days-in-AR, collections rate, and lag days — MHS and Radial benchmarks side-by-side", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "Monthly reporting to Integration Lead regardless of which model is chosen" },
      { id: "rcm-9", phase: "RCM Standards", owner: "Ops/RCM Lead", description: "Build MHS-to-Radial RCM standards crosswalk — document every process delta and produce a harmonization plan compatible with whichever model is selected", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "" },
      { id: "rcm-10", phase: "RCM Standards", owner: "Ops/RCM Lead", description: "Resolve all outstanding patient billing disputes surfaced in audit — direct patient outreach for affected accounts", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "One bad billing interaction = lost patient" },
      { id: "rcm-11", phase: "RCM Execution", owner: "Ops/RCM Lead", description: "Payer change-of-ownership notices drafted and filed across all payers at all 21 MHS locations — prevent claims interruption", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "File immediately regardless of RCM model decision" },
      { id: "rcm-12", phase: "RCM Execution", owner: "Ops/RCM Lead", description: "[Path-dependent] Execute selected RCM model transition per approved roadmap — milestone cadence and ownership defined post-decision", priority: "HIGH", monthTarget: "Month 3–6", status: "Not Started", notes: "Populated once decision is made in Month 2" },
      { id: "rcm-13", phase: "RCM Execution", owner: "Ops/RCM Lead", description: "Post-stabilization AR reconciliation — confirm no claims in limbo, no unpaid legacy denials, and clean AR handoff to ongoing ops", priority: "HIGH", monthTarget: "Month 6", status: "Not Started", notes: "" },
      { id: "rcm-14", phase: "RCM Execution", owner: "Ops/RCM Lead", description: "Full network RCM performance report: pre vs post integration metrics across all payers and locations — board-ready summary", priority: "HIGH", monthTarget: "Month 6", status: "Not Started", notes: "" },
    ],
  },
  {
    id: "ops",
    name: "Operations",
    objective: "Audit and unify Care Navigation (inbound calls through ongoing patient management) and Practice Manager/Technician structure across all locations, align with HR on staffing model and recruitment",
    owner: "Ops Lead",
    monthTarget: "Month 1–6",
    tasks: [
      { id: "ops-1", phase: "Care Nav Audit", owner: "Ops Lead", description: "Audit MHS inbound call handling end-to-end: call routing, hold times, abandonment rate, after-hours coverage, and call recording/QA practices", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "ops-2", phase: "Care Nav Audit", owner: "Ops Lead", description: "Audit MHS inquiry response process: channel coverage (phone, web form, chat, email), average response time, and conversion-to-discovery-call rate", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "ops-3", phase: "Care Nav Audit", owner: "Ops Lead", description: "Audit MHS discovery call process: script/structure, who conducts them, conversion rate to BI/BV, and scheduling tooling", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "ops-4", phase: "Care Nav Audit", owner: "Ops Lead", description: "Audit MHS benefits investigation (BI) and benefits verification (BV) workflow: tools used, turnaround time, accuracy rate, and handoff process to scheduling", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "ops-5", phase: "Care Nav Audit", owner: "Ops Lead", description: "Audit MHS scheduling process and tooling: booking workflow, no-show/cancellation handling, waitlist management, and double-booking prevention", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "ops-6", phase: "Care Nav Audit", owner: "Ops Lead", description: "Audit MHS ongoing patient management cadence: check-in calls, treatment progress follow-up, re-engagement of lapsed patients, and escalation pathways", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "ops-7", phase: "Care Nav Audit", owner: "Ops Lead + Tech Lead", description: "Audit the technology stack underlying Care Navigation at MHS: phone system, CRM, scheduling software, and BI/BV tools — map to Radial equivalents", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "ops-8", phase: "Care Nav Plan", owner: "Ops Lead", description: "Build a unified Care Navigation experience map spanning inbound call through ongoing management", priority: "CRITICAL", monthTarget: "Month 2", status: "Not Started", notes: "" },
      { id: "ops-9", phase: "Care Nav Plan", owner: "Ops Lead", description: "Identify process and tech gaps between current MHS state and target-state Care Navigation experience — build a phased closure plan", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "" },
      { id: "ops-10", phase: "Care Nav Plan", owner: "Ops Lead", description: "Define unified BI/BV SLA and quality standard across the combined network — turnaround time target and accuracy benchmark", priority: "HIGH", monthTarget: "Month 2–3", status: "Not Started", notes: "" },
      { id: "ops-11", phase: "Care Nav Rollout", owner: "Ops Lead", description: "Pilot unified Care Navigation workflow at 2–3 MHS locations — measure call handling time, conversion rate, and patient satisfaction vs baseline", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "ops-12", phase: "Care Nav Rollout", owner: "Ops Lead", description: "Train all MHS Care Navigation staff on unified process and tooling", priority: "HIGH", monthTarget: "Month 3–4", status: "Not Started", notes: "" },
      { id: "ops-13", phase: "Care Nav Rollout", owner: "Ops Lead", description: "Full network rollout of unified Care Navigation experience across all 21 MHS locations", priority: "HIGH", monthTarget: "Month 5", status: "Not Started", notes: "" },
      { id: "ops-14", phase: "Care Nav Rollout", owner: "Ops Lead", description: "Establish ongoing Care Navigation performance reporting: call metrics, conversion funnel, BI/BV turnaround, and patient satisfaction — monthly cadence", priority: "MEDIUM", monthTarget: "Month 6", status: "Not Started", notes: "" },
      { id: "ops-15", phase: "PM/Tech Audit", owner: "Ops Lead", description: "Audit Practice Manager structure across all 21 MHS locations: headcount, span of control, reporting lines, tenure, and current responsibilities", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "ops-16", phase: "PM/Tech Audit", owner: "Ops Lead", description: "Audit Technician staffing across all MHS locations: headcount, certification status, scheduling model, and utilization rate", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "ops-17", phase: "PM/Tech Audit", owner: "Ops Lead", description: "Compare MHS Practice Manager and Technician structure against Radial's organizational model — identify structural gaps or redundancies", priority: "HIGH", monthTarget: "Month 1–2", status: "Not Started", notes: "" },
      { id: "ops-18", phase: "PM/Tech Mgmt", owner: "Ops Lead + HR Lead", description: "Define target-state Practice Manager and Technician org structure for the combined network — roles, reporting lines, and span of control", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "" },
      { id: "ops-19", phase: "PM/Tech Mgmt", owner: "Ops Lead", description: "Build Practice Manager training curriculum covering Radial operating standards, RCM basics, Care Navigation oversight, and reporting expectations", priority: "HIGH", monthTarget: "Month 2–3", status: "Not Started", notes: "" },
      { id: "ops-20", phase: "PM/Tech Mgmt", owner: "Ops Lead", description: "Build Technician training and certification tracking program", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "ops-21", phase: "PM/Tech Mgmt", owner: "Ops Lead", description: "Roll out Practice Manager and Technician training across all 21 MHS locations", priority: "HIGH", monthTarget: "Month 3–4", status: "Not Started", notes: "" },
      { id: "ops-22", phase: "PM/Tech Reporting", owner: "Ops Lead", description: "Establish standardized Practice Manager reporting cadence: clinic-level operational metrics, staffing status, and escalation items — weekly or biweekly", priority: "MEDIUM", monthTarget: "Month 4", status: "Not Started", notes: "" },
      { id: "ops-23", phase: "PM/Tech Reporting", owner: "Ops Lead", description: "Deliver 6-month Practice Manager and Technician integration report", priority: "MEDIUM", monthTarget: "Month 6", status: "Not Started", notes: "" },
    ],
  },
  {
    id: "clinical",
    name: "Clinical Expansion",
    objective: "Review MHS TMS protocols (i.e. 2x/day, accelerated); protect Spravato continuity, set timeline for new modality introductions (i.e. prism, prolive, 2027 COMP360, etc)",
    owner: "ClinOps Lead",
    monthTarget: "Month 1–6",
    tasks: [
      { id: "clin-1", phase: "Assessment", owner: "Integration Lead + ClinOps", description: "Audit current MHS TMS protocols across all 21 locations — document which are running standard 1x/day and identify sites with capacity for 2x/day or accelerated protocols", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "MHS has strong TMS volume but all on standard 1x/day" },
      { id: "clin-2", phase: "Assessment", owner: "ClinOps", description: "Identify MHS clinicians most receptive to protocol expansion — flag KOLs who can become internal champions for accelerated and 2x TMS", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "Clinician buy-in is the rate-limiting variable" },
      { id: "clin-3", phase: "Assessment", owner: "ClinOps", description: "Inventory all MHS locations for PRISM readiness: space, power, workflow capacity, and staff bandwidth", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "PRISM is a Radial differentiator; MHS has zero current exposure" },
      { id: "clin-4", phase: "TMS Expansion", owner: "ClinOps", description: "Launch accelerated TMS protocol (dTMS or theta burst) at 3 pilot MHS sites — establish monitoring cadence and adverse event reporting", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "Pilot before network-wide rollout" },
      { id: "clin-5", phase: "TMS Expansion", owner: "ClinOps + RCM", description: "Convert existing MHS patients on standard TMS to 2x/day where clinically appropriate — build consent workflow and scheduling templates", priority: "HIGH", monthTarget: "Month 2–3", status: "Not Started", notes: "Revenue uplift and better clinical outcomes; do not rush conversions without consent workflow" },
      { id: "clin-6", phase: "TMS Expansion", owner: "Growth + ClinOps", description: "Update new patient intake process to include 2x/day and accelerated TMS as standard options", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "clin-7", phase: "TMS Expansion", owner: "ClinOps", description: "Full 2x/day TMS rollout across all 21 MHS locations — monitor utilization rate and patient retention week-over-week", priority: "CRITICAL", monthTarget: "Month 4", status: "Not Started", notes: "Network-wide only after pilot validates" },
      { id: "clin-8", phase: "PRISM", owner: "ClinOps + Tech", description: "Eval PRISM install hardware at first 3 MHS pilot sites — coordinate with vendor for site prep, device configuration, and staff orientation", priority: "CRITICAL", monthTarget: "Month 3", status: "Not Started", notes: "MHS team has no prior PRISM exposure — white-glove onboarding required" },
      { id: "clin-9", phase: "PRISM", owner: "ClinOps + Growth", description: "Build PRISM patient referral pathway at pilot sites — identify current MHS patients who are PRISM candidates (anxiety, performance, chronic pain, cognitive)", priority: "HIGH", monthTarget: "Month 3–4", status: "Not Started", notes: "Internal conversion before external marketing" },
      { id: "clin-10", phase: "PRISM", owner: "ClinOps", description: "Evaluate pilot outcomes and refine protocol before Phase 2 expansion", priority: "HIGH", monthTarget: "Month 4", status: "Not Started", notes: "" },
      { id: "clin-11", phase: "PRISM", owner: "ClinOps + Tech", description: "Phase 2 PRISM expansion: install at next 6–8 MHS locations based on pilot learnings and site readiness scores", priority: "HIGH", monthTarget: "Month 5", status: "Not Started", notes: "" },
      { id: "clin-12", phase: "PRISM", owner: "ClinOps", description: "Full PRISM network target: PRISM presence at all eligible MHS locations with trained staff and active patient pipelines", priority: "MEDIUM", monthTarget: "Month 6", status: "Not Started", notes: "Eligibility gated by space and staff capacity" },
      { id: "clin-13", phase: "Spravato", owner: "ClinOps", description: "Validate REMS Healthcare Setting status transferred correctly at all Spravato-administering MHS locations — zero disruption to existing patients", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "MHS is the 2nd largest US Spravato administrator — protect this asset" },
      { id: "clin-14", phase: "Spravato", owner: "ClinOps", description: "Share Radial Spravato operational best practices with MHS teams — exchange learnings bidirectionally", priority: "MEDIUM", monthTarget: "Month 2", status: "Not Started", notes: "" },
    ],
  },
  {
    id: "tech",
    name: "Technology & Systems",
    objective: "Full audit of all MHS physical technology (TMS machines, hardware, PRISM-ready spaces), IT infrastructure, SaaS contracts, and internal/external systems (EMR, RadialOS, patient portals, billing software, telehealth platforms); build a prioritized change plan with timing across all locations.",
    owner: "Tech Lead",
    monthTarget: "Month 1–6",
    tasks: [
      { id: "tech-1", phase: "Audit", owner: "Tech Lead", description: "Complete technology inventory across all 21 MHS locations: EMR/EHR, patient portal, billing software, scheduling tool, telehealth platform, and all physical device inventory (TMS machines, PRISM-ready spaces, other hardware)", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Produce a location-by-location register — physical + IT + external systems" },
      { id: "tech-2", phase: "Audit", owner: "Tech Lead", description: "Audit IT infrastructure at all sites: network topology, ISP contracts, hardware age, VPN and remote access setup, cybersecurity posture, and HIPAA technical safeguards compliance", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Flag any sites with legacy or non-compliant infrastructure immediately" },
      { id: "tech-3", phase: "Audit", owner: "Tech Lead", description: "Document all external software systems and SaaS contracts in use across MHS — map each to Radial equivalent or flag as net-new", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "Goal: identify redundant tools and rationalize the stack over time" },
      { id: "tech-4", phase: "Planning", owner: "Tech Lead", description: "Build Systems Decision Matrix: for each MHS tool and system, document Keep, Migrate, or Sunset decision with rationale, estimated timeline, and resource requirement", priority: "CRITICAL", monthTarget: "Month 2", status: "Not Started", notes: "Executive sign-off required before any migration begins" },
      { id: "tech-5", phase: "Planning", owner: "Tech Lead + ClinOps", description: "Design RadialOS integration plan for MHS locations — data migration architecture, user provisioning, training timeline, and parallel run approach by state cluster", priority: "CRITICAL", monthTarget: "Month 2", status: "Not Started", notes: "Phase by cluster; do not attempt a 21-location simultaneous migration" },
      { id: "tech-6", phase: "Planning", owner: "Tech Lead", description: "Plan physical device schedule: identify TMS machines requiring maintenance or replacement, PRISM installation requirements by site, and IT hardware refresh priorities", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "" },
      { id: "tech-7", phase: "RadialOS", owner: "Tech Lead", description: "Pilot RadialOS at 2 MHS locations (1 CA, 1 WA) — full workflow migration with dedicated tech support and a 2-week parallel run before cutover", priority: "CRITICAL", monthTarget: "Month 3", status: "Not Started", notes: "Do not cut over without parallel run confirmation and sign-off from site lead" },
      { id: "tech-8", phase: "RadialOS", owner: "Tech Lead", description: "Train MHS staff at pilot locations on RadialOS: scheduling, documentation, Spruce messaging, and patient management", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "tech-9", phase: "RadialOS", owner: "Tech Lead", description: "Phase 2 RadialOS rollout: CA cluster (14 locations) migrated — monitor error rates, user adoption, and support ticket volume daily", priority: "CRITICAL", monthTarget: "Month 4", status: "Not Started", notes: "" },
      { id: "tech-10", phase: "RadialOS", owner: "Tech Lead", description: "Phase 3 RadialOS rollout: TX and WA clusters — full 21-location network on RadialOS", priority: "CRITICAL", monthTarget: "Month 5", status: "Not Started", notes: "" },
      { id: "tech-11", phase: "Rationalization", owner: "Tech Lead", description: "Decommission all sunset tools and close legacy vendor accounts — confirm data export and retention compliance before any shutdown", priority: "HIGH", monthTarget: "Month 5–6", status: "Not Started", notes: "" },
      { id: "tech-12", phase: "Rationalization", owner: "Tech Lead", description: "Deliver integrated network tech stack report: all 21 locations on unified systems with ongoing IT support model defined", priority: "HIGH", monthTarget: "Month 6", status: "Not Started", notes: "" },
    ],
  },
  {
    id: "commercial",
    name: "Commercial & Payer",
    objective: "Audit all MHS payer contracts, identify renewal dates and rate gaps, and build a prioritized payer strategy for the combined network",
    owner: "Commercial Lead",
    monthTarget: "Month 1–5",
    tasks: [
      { id: "com-1", phase: "Audit", owner: "Commercial + RCM", description: "Pull all MHS payer contracts across CA, TX, and WA — document payer name, contract type, effective dates, renewal dates, and current reimbursement rates by CPT code", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Build a Payer Contract Register; flag all contracts expiring within 12 months" },
      { id: "com-2", phase: "Audit", owner: "Commercial", description: "Identify change-of-ownership notification requirements for each payer — draft and file COO notices immediately to prevent claims interruption", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Failure to notify payers = payment suspension risk; this cannot wait" },
      { id: "com-3", phase: "Audit", owner: "Commercial", description: "Map MHS payer mix by location and service line — identify concentration risk (any location above 40% single payer) and coverage gaps across all 21 sites", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "com-4", phase: "Audit", owner: "Commercial + RCM", description: "Cross-reference MHS contracted rates against Radial's best rates by CPT code — identify where MHS is under-contracted and prioritize for renegotiation", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "RadialONE MSO structure may unlock better rates via combined network leverage" },
      { id: "com-5", phase: "Strategy", owner: "Commercial", description: "Build MHS Payer Strategy document: prioritized list of contracts to renegotiate, new payers to pursue, and markets requiring in-network expansion", priority: "CRITICAL", monthTarget: "Month 2", status: "Not Started", notes: "CA Medi-Cal, Premera WA, and BCBS multi-state are top priorities" },
      { id: "com-6", phase: "Strategy", owner: "Commercial", description: "Initiate Premera Blue Cross (WA) outreach — position combined Radial and MHS network as single-TIN TMS administrator for WA commercial market", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "Premera deck (V6) already built; adapt for MHS network addition" },
      { id: "com-7", phase: "Strategy", owner: "Commercial", description: "Evaluate Medi-Cal managed care payer landscape across all 14 CA MHS locations — identify which MCOs cover TMS and Spravato", priority: "HIGH", monthTarget: "Month 2–3", status: "Not Started", notes: "14 CA locations represent significant Medi-Cal exposure and opportunity" },
      { id: "com-8", phase: "Strategy", owner: "Commercial + Legal", description: "Assess TRICARE and VA coverage at MHS locations with high military-adjacent populations (TX especially)", priority: "MEDIUM", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "com-9", phase: "Execution", owner: "Commercial", description: "Execute priority payer renegotiations — target rate parity with Radial best rates; use combined 21+ location network as leverage", priority: "HIGH", monthTarget: "Month 3–5", status: "Not Started", notes: "" },
      { id: "com-10", phase: "Execution", owner: "Commercial", description: "Establish quarterly payer strategy review cadence — track in-network status, rate changes, and denial trends across full MHS network", priority: "MEDIUM", monthTarget: "Month 4", status: "Not Started", notes: "" },
      { id: "com-11", phase: "BD Audit", owner: "Commercial Lead", description: "Audit MHS Business Development function: current team structure, headcount, and reporting lines across CA, TX, and WA", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "com-12", phase: "BD Audit", owner: "Commercial Lead", description: "Identify whether MHS BD operates under a national structure or is fully decentralized by region/location", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "com-13", phase: "BD Audit", owner: "Commercial Lead", description: "Identify MHS BD leadership: who owns BD strategy nationally, regional leads, and individual contributor roles", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "com-14", phase: "BD Audit", owner: "Commercial Lead", description: "Audit MHS BD training program: onboarding curriculum, ongoing training cadence, and materials/playbooks currently in use", priority: "MEDIUM", monthTarget: "Month 1–2", status: "Not Started", notes: "" },
      { id: "com-15", phase: "BD Audit", owner: "Commercial Lead", description: "Audit MHS BD management practices: goal-setting, pipeline tracking, performance review cadence, and compensation/incentive structure", priority: "MEDIUM", monthTarget: "Month 2", status: "Not Started", notes: "" },
      { id: "com-16", phase: "BD Audit", owner: "Commercial Lead", description: "Compare MHS BD model against Radial's BD structure and identify gaps, redundancies, and integration opportunities", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "" },
      { id: "com-17", phase: "BD Plan", owner: "Commercial Lead", description: "Develop a recommended national BD structure for the combined network — reporting lines, regional coverage model, and leadership roles", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "com-18", phase: "BD Plan", owner: "Commercial Lead", description: "Build a unified BD training and management framework — onboarding curriculum, pipeline tracking tool, and performance review standard", priority: "MEDIUM", monthTarget: "Month 3–4", status: "Not Started", notes: "" },
      { id: "com-19", phase: "BD Plan", owner: "Commercial Lead", description: "Present BD structure recommendation to leadership for review and approval", priority: "HIGH", monthTarget: "Month 4", status: "Not Started", notes: "" },
    ],
  },
  {
    id: "growth",
    name: "Growth & Marketing",
    objective: "Audit and rebuild MHS digital presence, update Radial's digital footprint, launch UGC engine, establish field marketing/local playbook and referral networks across all markets",
    owner: "Growth Lead",
    monthTarget: "Month 1–6",
    tasks: [
      { id: "gro-1", phase: "Audit", owner: "Growth Lead", description: "Audit all MHS digital properties: websites, Google Business Profiles (21 locations), social media accounts, online directories, and review platforms — claim all access credentials", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Claim or transfer all GBP listings on Day 1 — ownership of these profiles is a business asset" },
      { id: "gro-2", phase: "Audit", owner: "Growth Lead", description: "Review MHS paid media accounts (Google Ads, Meta) — audit spend, campaign structure, targeting, and conversion tracking across all active locations", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "Identify wasted spend and quick wins before rebuilding" },
      { id: "gro-3", phase: "Audit", owner: "Growth Lead", description: "Audit MHS online reputation: aggregate review scores by location, flag locations below 4.0 stars, and identify recurring negative review themes", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "gro-4", phase: "Audit", owner: "Growth Lead", description: "Assess field marketing activity at MHS locations: referral source relationships, community partnerships, and in-office marketing materials", priority: "MEDIUM", monthTarget: "Month 1", status: "Not Started", notes: "" },
      { id: "gro-5", phase: "Digital", owner: "Growth Lead", description: "Migrate all MHS location pages to Radial website architecture — consistent URL structure, SEO metadata, service line pages, and provider bios", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "Preserve any high-authority MHS URLs via 301 redirect to protect SEO equity" },
      { id: "gro-6", phase: "Digital", owner: "Growth Lead", description: "Launch standardized paid media campaigns for all 21 MHS locations — use Radial's proven TMS, Spravato, and PRISM campaign templates adapted for local market keywords", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "" },
      { id: "gro-7", phase: "Digital", owner: "Growth Lead", description: "Build UGC engine at MHS locations: post-completion review ask workflow, video testimonial capture process, and social amplification playbook", priority: "HIGH", monthTarget: "Month 2–3", status: "Not Started", notes: "UGC is the highest-trust content format in mental health" },
      { id: "gro-8", phase: "Field", owner: "Growth Lead", description: "Map referral source landscape for each MHS location: PCPs, psychiatrists, therapists, hospitals, VA and military, and employer EAP programs", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "gro-9", phase: "Field", owner: "Growth Lead", description: "Launch field marketing program at top 5 MHS locations by volume — provider lunch-and-learns, CME events, and community education partnerships", priority: "HIGH", monthTarget: "Month 3–4", status: "Not Started", notes: "" },
      { id: "gro-10", phase: "Field", owner: "Growth Lead", description: "Build referral source tracking in Metabase — source attribution by location, referral conversion rates, and ROI by channel for all 21 MHS markets", priority: "MEDIUM", monthTarget: "Month 4", status: "Not Started", notes: "" },
      { id: "gro-11", phase: "Network", owner: "Growth Lead", description: "Full digital activation across all 21 MHS locations — all campaigns live, GBP optimized, UGC pipeline operational, and field reps deployed in top markets", priority: "HIGH", monthTarget: "Month 5", status: "Not Started", notes: "" },
      { id: "gro-12", phase: "Network", owner: "Growth Lead", description: "Monthly growth reporting: patient acquisition by channel, location, and service line — benchmark against Radial network average", priority: "MEDIUM", monthTarget: "Month 5", status: "Not Started", notes: "" },
      { id: "gro-13", phase: "Brand Audit", owner: "Growth Lead", description: "Audit the Radial brand: logo, color system, typography, voice/tone guidelines, and current brand equity across existing markets", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "Baseline before any comparison work begins" },
      { id: "gro-14", phase: "Brand Audit", owner: "Growth Lead", description: "Audit the MHS brand: logo, color system, typography, voice/tone, and brand equity/recognition across CA, TX, and WA markets", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "MHS may have stronger regional recognition than Radial in some areas" },
      { id: "gro-15", phase: "Brand Audit", owner: "Growth Lead", description: "Assess brand equity and patient/referral source recognition for both brands in overlapping and non-overlapping markets", priority: "HIGH", monthTarget: "Month 1–2", status: "Not Started", notes: "" },
      { id: "gro-16", phase: "Brand Discussion", owner: "Growth Lead + Integration Lead", description: "Facilitate working sessions on brand unification options: full rebrand to Radial, dual-brand strategy, or MHS retained as a sub-brand", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "Exploratory only — no decision at this stage" },
      { id: "gro-17", phase: "Brand Discussion", owner: "Growth Lead", description: "Research comparable behavioral health M&A brand integration approaches", priority: "MEDIUM", monthTarget: "Month 2", status: "Not Started", notes: "" },
      { id: "gro-18", phase: "Brand Discussion", owner: "Growth Lead", description: "Assess SEO, paid media, and digital migration cost/complexity under each brand scenario", priority: "MEDIUM", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "gro-19", phase: "Brand Plan", owner: "Growth Lead", description: "Develop a formal Brand Unification Plan document outlining all viable paths, recommended evaluation criteria, and a recommended decision timeline", priority: "HIGH", monthTarget: "Month 3–4", status: "Not Started", notes: "Deliverable is a plan and recommendation framework — final decision remains with leadership" },
      { id: "gro-20", phase: "Brand Plan", owner: "Growth Lead", description: "Present Brand Unification Plan to Integration Lead and leadership for review", priority: "HIGH", monthTarget: "Month 4", status: "Not Started", notes: "" },
    ],
  },
  {
    id: "hr",
    name: "HR & People Ops",
    objective: "Migrate all MHS/Radial staff into a single Rippling account, execute recruitment plan, formalize reviews and org charts, protect key talent, manage retention targets, and align benefits and policies to Radial standards",
    owner: "HR Lead",
    monthTarget: "Month 1–5",
    tasks: [
      { id: "hr-1", phase: "Comms", owner: "Integration Lead", description: "Issue Day 1 all-staff welcome communication to all 21 MHS locations — introduce Radial mission, values, leadership team, and what changes vs what stays the same", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Written and video where possible; never miss a Friday update cadence" },
      { id: "hr-2", phase: "Inventory", owner: "HR Lead", description: "Complete people inventory across all 21 locations: headcount by role, employment type (W2 or 1099), compensation, tenure, and reporting structure", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Flag any non-standard comp arrangements or verbal promises made during acquisition process" },
      { id: "hr-3", phase: "Org Chart", owner: "HR Lead", description: "Build and publish Rippling org chart for MHS integration: reporting lines from all 21 locations through state cluster leads to Integration Lead and executive team", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "Publish to all staff — reducing ambiguity about who reports to whom is a retention tool" },
      { id: "hr-4", phase: "Credentialing", owner: "HR Lead + ClinOps", description: "Verify clinical credentialing and licensure for all MHS licensed providers — flag upcoming expirations and initiate renewal workflows immediately", priority: "CRITICAL", monthTarget: "Month 2", status: "Not Started", notes: "WA DOH credentialing has a 60–90 day lag — initiate on Day 1 or Day 2 at the latest" },
      { id: "hr-5", phase: "Culture", owner: "HR Lead + Integration Lead", description: "Deploy all-staff culture survey at MHS locations — measure morale, operational satisfaction, management confidence, and awareness of Radial mission", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "Establishes baseline for tracking culture integration over time" },
      { id: "hr-6", phase: "Policy", owner: "HR Lead + Legal", description: "Audit MHS employee handbook and HR policies — identify gaps vs Radial standards in PTO, leave, conduct, and clinical credentialing requirements", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "hr-7", phase: "Benefits", owner: "HR Lead", description: "Migrate MHS staff to Radial benefits plan — coordinate open enrollment, communicate all changes clearly, and ensure zero gaps in coverage during transition", priority: "CRITICAL", monthTarget: "Month 3", status: "Not Started", notes: "Benefits transition is high morale-risk — communicate early, clearly, and repeatedly" },
      { id: "hr-8", phase: "Compliance", owner: "HR Lead", description: "Complete I-9 and employment eligibility audit for all MHS W2 employees — remediate any documentation gaps", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "hr-9", phase: "Retention", owner: "HR Lead", description: "Conduct retention pulse survey at MHS locations — measure changes in morale, confidence in leadership, and intent to stay vs Month 2 baseline", priority: "HIGH", monthTarget: "Month 5", status: "Not Started", notes: "" },
      { id: "hr-10", phase: "Report", owner: "HR Lead", description: "Deliver 6-month HR integration report: turnover rate, open roles, compensation parity analysis, and culture integration score", priority: "HIGH", monthTarget: "Month 6", status: "Not Started", notes: "" },
    ],
  },
  {
    id: "px",
    name: "Patient Experience",
    objective: "Establish NPS baseline, audit MHS locations, deploy Radial hospitality standards, prioritize and execute clinic upgrades, and define community channel strategy across all MHS sites",
    owner: "PX Lead",
    monthTarget: "Month 1–6",
    tasks: [
      { id: "px-1", phase: "Aesthetic", owner: "PX Lead", description: "Conduct in-person clinic aesthetic assessment at all 21 MHS locations — score each site on cleanliness, signage, furniture condition, brand alignment, and patient-facing environment quality", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Produce a Clinic Aesthetic Scorecard: Green (ready), Yellow (minor upgrade needed), Red (redesign or repair required)" },
      { id: "px-2", phase: "NPS", owner: "PX Lead", description: "Establish NPS baseline at all 21 MHS locations — deploy Radial NPS survey protocol, capture first data set, and flag any locations below network floor", priority: "CRITICAL", monthTarget: "Month 1", status: "Not Started", notes: "Baseline is prerequisite to recovery trajectory planning; do not skip any location" },
      { id: "px-3", phase: "Journey", owner: "PX Lead", description: "Audit patient journey at 3 MHS locations (1 CA, 1 WA, 1 TX) — map every touchpoint from first contact through discharge; shadow intake, treatment session, and discharge in person", priority: "HIGH", monthTarget: "Month 1", status: "Not Started", notes: "Do not rely on staff description of the journey — observe it directly" },
      { id: "px-4", phase: "Standards", owner: "PX Lead", description: "Deploy Radial Patient Experience Standards at all MHS locations: unreasonable hospitality protocol, care journey communication cadence, and service standards training for all patient-facing staff", priority: "CRITICAL", monthTarget: "Month 2", status: "Not Started", notes: "Do not assume MHS staff know what Radial hospitality looks like — show and train, do not just share a document" },
      { id: "px-5", phase: "Celebrations", owner: "PX Lead", description: "Launch Completion Celebrations at all MHS locations — adapt Radial's celebration model for MHS patient demographics and each clinic's culture", priority: "HIGH", monthTarget: "Month 2", status: "Not Started", notes: "Completion Celebrations drive UGC, referrals, and NPS simultaneously" },
      { id: "px-6", phase: "Comms", owner: "PX Lead", description: "Implement care journey communication standards: intake confirmation, appointment reminders, mid-treatment check-ins, and post-treatment follow-up at all 21 sites", priority: "HIGH", monthTarget: "Month 2–3", status: "Not Started", notes: "Deploy via Spruce post-Tech migration; use interim solution if Tech migration is delayed" },
      { id: "px-7", phase: "Upgrades", owner: "PX Lead", description: "Execute Red-tier clinic upgrades: develop repair or redesign scope for each flagged location, vendor-select, and drive execution", priority: "HIGH", monthTarget: "Month 2–4", status: "Not Started", notes: "PX Lead owns the outcome; Site Ops Lead owns the logistics" },
      { id: "px-8", phase: "Upgrades", owner: "PX Lead", description: "Complete Yellow-tier clinic improvements: furniture, signage, paint, and branding touches — prioritize high-volume and high-visibility locations first", priority: "MEDIUM", monthTarget: "Month 3–4", status: "Not Started", notes: "" },
      { id: "px-9", phase: "NPS Recovery", owner: "PX Lead", description: "Implement NPS recovery plan at sub-standard locations — identify root causes (billing friction, wait times, staff demeanor, space quality), assign owners, and set 90-day recovery targets", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "" },
      { id: "px-10", phase: "NPS", owner: "PX Lead", description: "Launch monthly NPS reporting across all MHS locations — track trajectory toward Radial network standard; escalate any location showing a declining trend", priority: "HIGH", monthTarget: "Month 3", status: "Not Started", notes: "Report to Integration Lead monthly" },
      { id: "px-11", phase: "Community", owner: "PX Lead + Growth", description: "Define community channel strategy for each MHS market — identify local community anchors and design a presence model", priority: "MEDIUM", monthTarget: "Month 4", status: "Not Started", notes: "Define and hand off to Growth and Marketing for ongoing execution" },
      { id: "px-12", phase: "Audit", owner: "PX Lead", description: "Conduct final PX audit across all 21 locations — confirm aesthetic standards met, NPS trajectory positive, celebration protocol live, and community strategy handed off", priority: "HIGH", monthTarget: "Month 5–6", status: "Not Started", notes: "" },
      { id: "px-13", phase: "Report", owner: "PX Lead", description: "Deliver 6-month Patient Experience Integration Report — NPS delta, clinic upgrade completion, staff training completion, and UGC volume", priority: "HIGH", monthTarget: "Month 6", status: "Not Started", notes: "" },
    ],
  },
];
